### PR TITLE
Projects Page initial commit for branch creation

### PR DESCRIPTION
**Pull request by Arunteja27**
Initial commit to make branch & PR, sup.

### CODE REVIEW

**Comment by Arunteja27** [comment]
PR changes look like this: 

image

image


@heyitsOK  Mostly figured it out, need some help in how to properly size the images, can't seem to find the right ratio

**Comment by Arunteja27** [comment]
Also the figma design had a GitHub logo for current projects, idk where to find that info/if it exists. Ty & sorry for the delay!

**Comment by voidranjer** [comment]
> Also the figma design had a GitHub redirect for current projects, idk where to find that info/if it exists. Ty & sorry for the delay!

@Arunteja27 the details for each project should be in this link:
https://cublueprint.notion.site/f0725682a6134d0f8174876e083eee19?v=377b75cffcbb40ab828615826f3579f5

There should be GitHub links / live demo links in those pages, and if some projects don't have links then those are probably lost forever lol

**Comment by voidranjer** [comment]
The Projects Page is starting to look real good @Arunteja27 ! Great work :>

Just a couple of things left to address before I approve this PR:
- The links to each project's GitHub / live demo is attached to in the previous comment
- Can we make the current project cards wider?
- I noticed a gap between the sections near the bottom of the page. If you could fix that it would be great!

image

Tomorrow I'll take a look at the backgrounds that you were talking about, but for now, if you need any help with any of these things (or if you have any thoughts / feedback), drop them here or let us know! Great work g :>

**Comment by heyitsOK** [comment]
> * I noticed a gap between the sections near the bottom of the page. If you could fix that it would be great!

this i have already fixed on the pr i opened with jason so no need to worry about this one. it should be fixed once he rebases

**Comment by Arunteja27** [comment]
I've made a teeny change to make the image's for each past project bigger, it looks ok until we reach Beneficent's logo. 

image

**Review by voidranjer — APPROVED** [review]

**Pull request merged**
