### PR TITLE
Create new contact page

### PR DESCRIPTION
**Pull request by heyitsOK**
Add new directory and files for contact page. Create ContactCard component and use for every contact card, Use Card component from shadcn and fetch ContactCardDataType[] from Contentful. Add email section for nonprofit organization.

### CODE REVIEW

**Comment by heyitsOK** [comment]
I'm having trouble deciding how to style the social media section on the contact page. Please give your opinion on what parts you like/don't like in any of the options and I'll experiment a little bit. Here's option A:
image
image

**Comment by heyitsOK** [comment]
Here is option B:
image
image

**Comment by heyitsOK** [comment]
Here is option C:
image
image
Option C being just a straight line cutoff between the div's is more boring but also safest design choice so I'll leave it like that for now

**Comment by voidranjer** [comment]
I like **option B** a lot because it's a good blend between option A and option C!
- Option A looks good but the contrast between the background and foreground items doesn't stand out as much as in options B and C.
- Option C has good contrast but option B does it even better with the wavy borders

**Pull request merged**
