### PR TITLE
Added Prettier and ESLint to pipeline (build fails on warnings)

### LINKED ISSUE #111: Add Prettier and ESLint to pipeline (fail build on warnings)

### PR DESCRIPTION
**Pull request by heyitsOK**
# Description of Changes

Added prettier and eslint configs and setup formatting and linting commands in package.json. Build command will now run formatting and linting commands and fail on warnings/errors. This way any code submission should be formatted and linted before merging and if there are any errors we will be able to see them on preview deloyment build logs.

## Related Issues

- Closes #111 

## Checklist

- [x] MR title is meaningful and accurate
- [x] This MR has an associated GitHub Issues ticket
- [ ] ~GitHub Issues ticket fix version for this issue is correct~
- [ ] ~[Changelog entry](https://keepachangelog.com/en/1.0.0/) has been made~
- [x] I promise that my commit message for this MR will be clear, meaningful,
      and useful to others. I will ensure this by editing the final commit message
      in GitHub prior to merging

If a checklist item is completed for this MR, place an `x` inside of the square
brackets for that item. If a checklist item is not applicable for this MR, please
note that by wrapping that line with `~` characters, ~like this~.

> Make sure you squash your commits before merging!

### CODE REVIEW

**Comment by heyitsOK** [comment]
Here are the [preview deployment](https://deploy.cublueprint.org/project/uc008cgk8wwk8osookkkccoc/production/application/z8o0ows0k0s4owg0wcsg8kw0/deployment/dcogwck0480s0kw88s4wk4s4) logs before full repo formatting

**Comment by heyitsOK** [comment]
Here are the [preview deployments](https://deploy.cublueprint.org/project/uc008cgk8wwk8osookkkccoc/production/application/z8o0ows0k0s4owg0wcsg8kw0/deployment/ng0808oc488g4sksswg8so4c) logs before full repo linting

**Comment by heyitsOK** [comment]
Here are the [preview deployment](https://deploy.cublueprint.org/project/uc008cgk8wwk8osookkkccoc/production/application/z8o0ows0k0s4owg0wcsg8kw0/deployment/cosgs04owkgoogw0kos844ok) logs after full repo linting and formatting (Success ✅)

**Comment by heyitsOK** [comment]
I think we should clean up the logs on coolify so its easier to read when the build fails due to formatting or linting

**Review by voidranjer — APPROVED** [review]

**Comment by voidranjer** [comment]
This is wonderful work. Now there's 0% chance of eye twitching when looking at code 🎉

**Pull request merged**
